<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Name Drop</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style>
        body {
            margin: 50px 0 0 0;
            padding: 0;
            width: 100%;
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            text-align: center;
            color: #aaa;
            font-size: 18px;
        }

        h1 {
            color: #719e40;
            letter-spacing: -3px;
            font-family: 'Lato', sans-serif;
            font-size: 100px;
            font-weight: 200;
            margin-bottom: 0;
        }
    </style>
</head>
<body>

<h1>Welcome to NameDrop</h1>
<div>a study in CRUD, Git, unit testing, and separation of service</div>

<?php if (isset($name)) : ?>
<h2>Welcome <?= htmlspecialchars($name); ?>!</h2>
<?php endif; ?>

<div align="center">
<div align="left">
<?php
foreach ($people as $person):
    $name = $person->getName();
    $id   = $person->getId();
    echo "<div><a href='/delete/$id'>x</a> $name</div>";
endforeach;
?>
</div>
</div>

<form method="POST" action="/new/">
    <h2>Drop a Name:</h2>
    <input type="text" required name="name" placeholder="Name one...">
    <button type="submit">Do it</button>
</form>

<p>Looking for more? <a href="https://therapists.psychologytoday.com">Find a Therapist</a>

</body>
</html>
