<?php require "_head.phtml"; ?>

<body onload="setTimeout(function() {
    el = document.getElementById('message');
    el.style.visibility='hidden';
    el.style.display='block';
}, 3000);">

<h1>Welcome to NameDrop</h1>
<div>A study in CRUD, Git, unit testing, and separation of service</div>

<?php if (isset($message)) : ?>
<h3 id="message" style="visibility:visible"><?= htmlspecialchars($message); ?>!</h3>
<?php endif; ?>

<div align="center">
    <div align="left" style="width: 34%;">
        <?php
        foreach ($people as $person):
            $name = prerender($person->getName());
            $id   = $person->getId();
            $del = delButton("/delete/$id", "Delete");
            echo "<div>$del $name</div>";
        endforeach;
        ?>
    </div>
</div>

<form method="POST" action="/new/">
    <h2>Drop a Name:</h2>
    <input type="text" required name="name" placeholder="Name one...">
    <button type="submit">Do it</button>
</form>

<?php require "_foot.phtml"; ?>